### ISSUE TITLE
foundation5 javascripts not loaded

### ISSUE THREAD

**Issue by spoetnik** [dougmacklin/generator-foundation-browserify#4]
when using Foundation 5 (haven't tested with 6) the Foundation javascript isn't loaded.
Reveal and the Accordion aren't working.

Any suggestions?

**Comment by bsodmike** [comment]
I make a fork of this repo and added Foundation 6, not having any problems from my last tests
https://github.com/bsodmike/generator-gulp-foundation-sass-babel-browserify

**Comment by dougmacklin** [comment]
Hi @spoetnik, thanks for discovering that issue! Apparently the Foundation 5 javascript does not work with jQuery versions newer than 2.1.4 ([bug report](http://foundation.zurb.com/forum/posts/37587-uncaught-typeerror-modalontrigger-is-not-a-function-when-using-zurb-foundation-553)). This is now fixed - I set Foundation 5 projects to require that version exactly (commit: 5006fb9f18ee4e37cbd49b9cfcd3480fd292e33a).

Please run `yo` and select `Update your generators`. Let me know if you are still experiencing issues.

<hr>

@bsodmike - this issue was related specifically to a conflict with Foundation 5. This repository fully supports both Foundation 5 and 6, thanks.

**Comment by spoetnik** [comment]
Sweet! Thanks. Works like a charme now
